# Generated by Django 4.2.30 on 2026-07-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='weight',
            field=models.PositiveIntegerField(default=1, help_text='Relative importance weight (e.g. major milestone = 5, minor = 1). Used in physical progress calculation.'),
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=255)),
                ('phase_type', models.CharField(choices=[('planning', 'Planning'), ('implementation', 'Implementation'), ('monitoring', 'Monitoring & Evaluation'), ('closeout', 'Closeout')], max_length=50)),
                ('allocated_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project')),
            ],
            options={
                'db_table': 'project_phases',
                'ordering': ['start_date'],
            },
        ),
    ]
