# Generated by Django 4.2.30 on 2026-07-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_phase_opening_spend_milestone_completed_by_report'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('distribution', 'Distribution'), ('construction', 'Construction'), ('survey', 'Survey / Assessment'), ('community_meeting', 'Community Meeting'), ('monitoring', 'Monitoring Visit'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='report',
            name='amount_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='report',
            name='beneficiaries_female',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='beneficiaries_male',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='beneficiaries_reached',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='beneficiaries_youth',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='challenges_faced',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='expenditure_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='impact_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='linked_milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='projects.milestone'),
        ),
        migrations.AddField(
            model_name='report',
            name='linked_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='projects.projectphase'),
        ),
        migrations.AddField(
            model_name='report',
            name='next_steps',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='recommendations',
            field=models.TextField(blank=True),
        ),
    ]
