# Generated by Django 4.2.30 on 2026-07-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiary',
            name='location',
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='village',
            field=models.CharField(blank=True, help_text='Village or sub-location', max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='ward',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
