# Generated by Django 4.2.30 on 2026-07-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0002_remove_beneficiary_location_beneficiary_constituency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='location',
            field=models.CharField(blank=True, help_text='Location within ward', max_length=255),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='sub_location',
            field=models.CharField(blank=True, help_text='Sub-location within location', max_length=255),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='village',
            field=models.CharField(blank=True, help_text='Village (free text)', max_length=255),
        ),
    ]
